/**
 * MockJ — Terms of Service
 * Route: /terms
 */
import { useNavigate } from 'react-router-dom';
import logoImg from '@/assets/mockj-logo.png';

const RED = 'hsl(4 90% 58%)';

const SECTIONS = [
  {
    number: '1',
    title: 'Acceptance of Terms',
    content: `By accessing or using MockJ ("the Platform"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, do not use the Platform. We reserve the right to update these Terms at any time; continued use of the Platform after changes constitutes acceptance of the revised Terms. We will notify users of material changes via email or an in-app notification.`,
  },
  {
    number: '2',
    title: 'User Conduct & Eligibility',
    content: null,
    bullets: [
      {
        label: 'Age Requirement',
        text: 'You must be at least 13 years of age to use MockJ. Users under 18 must have verifiable parental or guardian consent. If MockJ discovers a user is under 13, that account will be deleted immediately.',
      },
      {
        label: 'No Reverse Engineering',
        text: 'You may not reverse engineer, decompile, disassemble, or attempt to derive the source code of any part of the Platform, nor scrape the Platform\'s data without express written permission.',
      },
      {
        label: 'No Harmful or Illegal Activity',
        text: 'You may not use the Platform to facilitate crimes, harassment, defamation, hate speech, infringement of intellectual property, or any activity that violates applicable local, state, national, or international laws or regulations.',
      },
      {
        label: 'Account Security',
        text: 'You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. Notify us immediately at legal@mockj.ai if you suspect unauthorized access.',
      },
    ],
  },
  {
    number: '3',
    title: 'Intellectual Property (IP)',
    content: null,
    bullets: [
      {
        label: 'Our Intellectual Property',
        text: 'All code, software, logos, UI/UX designs, original content, trademarks, and trade dress of MockJ and MLTXPRO are the exclusive property of MockJ / MLTXPRO and are protected by applicable intellectual property laws. Unauthorized reproduction or distribution is strictly prohibited.',
      },
      {
        label: 'Your Content',
        text: 'You retain ownership of all inputs, data, and content you provide to the Platform. By submitting content, you grant MockJ a non-exclusive, worldwide, royalty-free license to process, store, and display that content solely to deliver the services you request. We do not claim ownership of your content.',
      },
      {
        label: 'Generated Content',
        text: 'Content generated by the AI on your behalf (text, images, code, video) is provided for your use. Free-tier generated images are for personal, non-commercial use only. MockJ Pro subscribers receive a commercial license for AI-generated images. You are responsible for ensuring your use of generated content complies with applicable law.',
      },
    ],
  },
  {
    number: '4',
    title: 'Termination of Service',
    content: `MockJ reserves the right to suspend or permanently terminate any account, at any time, with or without notice, for any reason — including but not limited to violation of these Terms, fraudulent activity, or behavior that harms the community or platform integrity. Accounts terminated for violations are not entitled to a refund for unused subscription time or token balances. If you believe your account was terminated in error, contact support@mockj.ai.`,
  },
  {
    number: '5',
    title: 'Limitation of Liability',
    content: null,
    bullets: [
      {
        label: '"As Is" Service',
        text: 'The Platform is provided "AS IS" and "AS AVAILABLE" without warranties of any kind, either express or implied, including but not limited to implied warranties of merchantability, fitness for a particular purpose, or non-infringement.',
      },
      {
        label: 'No Liability for Downtime or Data Loss',
        text: 'MockJ shall not be liable for any loss of data, service interruptions, unauthorized access, or any indirect, incidental, special, consequential, or punitive damages arising out of or related to your use of the Platform.',
      },
      {
        label: 'Cap on Damages',
        text: 'In no event shall MockJ\'s aggregate liability to you for any claims arising out of or related to these Terms exceed the total amount you paid us in the six (6) months immediately preceding the event giving rise to the claim.',
      },
      {
        label: 'Reliance on AI Output',
        text: 'AI-generated content is provided for informational and creative purposes only. MockJ is not responsible for decisions made based on AI output. Always verify critical information from authoritative sources.',
      },
    ],
  },
  {
    number: '6',
    title: 'Indemnification',
    content: `You agree to defend, indemnify, and hold harmless MockJ, MLTXPRO, their affiliates, officers, directors, employees, agents, licensors, and service providers from and against any and all claims, liabilities, damages, judgments, awards, losses, costs, expenses, or fees (including reasonable attorneys' fees) arising out of or relating to (a) your violation of these Terms; (b) your use of the Platform in a manner not authorized by these Terms; or (c) your violation of any third party's rights, including intellectual property rights.`,
  },
  {
    number: '7',
    title: 'Payments, Subscriptions & Refunds',
    content: null,
    bullets: [
      {
        label: 'Billing',
        text: 'Paid subscriptions are billed in advance on a monthly or annual basis. All payments are processed securely through Stripe. By providing payment information, you authorize us to charge your payment method for the subscription fees.',
      },
      {
        label: 'Cancellations',
        text: 'You may cancel your subscription at any time through your account settings or by contacting support@mockj.ai. Cancellation takes effect at the end of the current billing period; you will not be charged for subsequent periods.',
      },
      {
        label: 'No Refunds on Tokens',
        text: 'MockJ tokens (platform credits) are non-refundable once purchased or consumed. Unused token balances are forfeited upon account termination for cause.',
      },
      {
        label: 'Price Changes',
        text: 'MockJ reserves the right to change subscription pricing at any time. We will provide at least 30 days\' notice of any price increase. Continued use after the effective date constitutes acceptance of the new pricing.',
      },
    ],
  },
  {
    number: '8',
    title: 'Arbitration & Dispute Resolution',
    content: `To the fullest extent permitted by law, any dispute arising out of or relating to these Terms or your use of the Platform shall be resolved through binding individual arbitration administered by the American Arbitration Association (AAA) under its Consumer Arbitration Rules, rather than in court. You waive your right to participate in a class action lawsuit or class-wide arbitration. Nothing in this section prevents either party from seeking injunctive or other equitable relief in court for intellectual property infringement or misappropriation.`,
  },
  {
    number: '9',
    title: 'Governing Law',
    content: `These Terms are governed by and construed in accordance with the laws of the State of Delaware, United States, without regard to its conflict-of-law provisions. To the extent court proceedings are permitted under Section 8, you consent to the exclusive jurisdiction of the state and federal courts located in Delaware.`,
  },
  {
    number: '10',
    title: 'Miscellaneous',
    content: null,
    bullets: [
      {
        label: 'Entire Agreement',
        text: 'These Terms, together with our Privacy Policy, constitute the entire agreement between you and MockJ regarding the Platform and supersede all prior agreements.',
      },
      {
        label: 'Severability',
        text: 'If any provision of these Terms is found unenforceable, the remaining provisions will remain in full force and effect.',
      },
      {
        label: 'Waiver',
        text: 'MockJ\'s failure to enforce any right or provision shall not constitute a waiver of that right or provision.',
      },
      {
        label: 'Contact',
        text: 'For questions about these Terms, contact us at legal@mockj.ai.',
      },
    ],
  },
];

export default function TermsOfServicePage() {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-[hsl(224_20%_4%)] text-foreground" style={{ fontFamily: 'Inter, sans-serif' }}>

      {/* Nav */}
      <nav className="sticky top-0 z-50 flex items-center gap-4 px-6 py-3 border-b border-white/5 backdrop-blur-xl bg-[hsl(224_20%_4%_/_0.92)]">
        <button onClick={() => navigate('/landing')} className="flex items-center gap-2.5">
          <div className="w-7 h-7 rounded-lg overflow-hidden">
            <img src={logoImg} alt="MockJ" className="w-full h-full object-cover" />
          </div>
          <span className="font-black text-sm text-foreground" style={{ fontFamily: 'Space Grotesk, sans-serif' }}>
            MockJ <span style={{ color: RED }}>4</span>
          </span>
        </button>
        <div className="flex-1" />
        <button
          onClick={() => navigate('/')}
          className="px-4 py-1.5 rounded-lg text-xs font-bold transition-all active:scale-95"
          style={{ background: RED, color: '#fff' }}
        >
          Launch App
        </button>
      </nav>

      {/* Header */}
      <header className="py-16 px-6 text-center border-b border-white/[0.04]" style={{ background: 'hsl(224 15% 6%)' }}>
        <div className="max-w-3xl mx-auto">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full border mb-6 text-xs font-bold" style={{ borderColor: 'hsl(4 90% 58% / 0.3)', color: RED, background: 'hsl(4 90% 58% / 0.07)' }}>
            Legal Document
          </div>
          <h1 className="text-4xl sm:text-5xl font-black tracking-tight mb-4" style={{ fontFamily: 'Space Grotesk, sans-serif' }}>
            Terms of Service
          </h1>
          <p className="text-muted-foreground text-base">
            Last updated: June 2025 &nbsp;·&nbsp; Effective immediately
          </p>
          <p className="text-muted-foreground/60 text-sm mt-3 max-w-xl mx-auto leading-relaxed">
            These Terms govern your access to and use of MockJ, operated by MLTXPRO.
            Please read them carefully before using the platform.
          </p>
        </div>
      </header>

      {/* Content */}
      <main className="max-w-3xl mx-auto px-6 py-16 space-y-12">
        {SECTIONS.map((section) => (
          <section key={section.number}>
            <div className="flex items-start gap-4 mb-4">
              <div
                className="w-8 h-8 rounded-lg flex items-center justify-center text-xs font-black shrink-0 mt-0.5"
                style={{ background: 'hsl(4 90% 58% / 0.12)', border: '1px solid hsl(4 90% 58% / 0.25)', color: RED }}
              >
                {section.number}
              </div>
              <h2 className="text-xl font-bold text-foreground pt-1" style={{ fontFamily: 'Space Grotesk, sans-serif' }}>
                {section.title}
              </h2>
            </div>
            {section.content && (
              <p className="text-sm text-muted-foreground leading-relaxed ml-12">
                {section.content}
              </p>
            )}
            {section.bullets && (
              <ul className="ml-12 space-y-3">
                {section.bullets.map((b) => (
                  <li key={b.label} className="text-sm text-muted-foreground leading-relaxed">
                    <span className="font-semibold text-foreground/80">{b.label}: </span>
                    {b.text}
                  </li>
                ))}
              </ul>
            )}
          </section>
        ))}

        {/* Disclaimer box */}
        <div
          className="rounded-2xl p-6 text-sm text-muted-foreground leading-relaxed"
          style={{ background: 'hsl(224 15% 7%)', border: '1px solid hsl(224 15% 13%)' }}
        >
          <p className="font-semibold text-foreground/70 mb-2">⚠ Legal Notice</p>
          <p>
            This Terms of Service is provided as a general framework and does not constitute legal advice.
            For a final, legally binding version tailored to your jurisdiction and specific circumstances,
            consult a licensed attorney. Laws governing technology platforms vary by state and country and
            change frequently.
          </p>
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-white/[0.04] py-8 px-6">
        <div className="max-w-3xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-3 text-xs text-muted-foreground/50">
          <span>© 2025 MockJ · MLTXPRO · All rights reserved.</span>
          <div className="flex items-center gap-4">
            <button onClick={() => navigate('/privacy')} className="hover:text-foreground transition-colors">Privacy Policy</button>
            <span className="opacity-30">·</span>
            <button onClick={() => navigate('/terms')} className="hover:text-foreground transition-colors" style={{ color: RED }}>Terms of Service</button>
            <span className="opacity-30">·</span>
            <a href="mailto:legal@mockj.ai" className="hover:text-foreground transition-colors">legal@mockj.ai</a>
          </div>
        </div>
      </footer>
    </div>
  );
}
